DATA_PATH = r"C:\Users\user\Desktop\NN-Faces\data"
ITERATION_TRAIN = 10000
WEIGHT_MIN = -1
WEIGHT_MAX = 1
IMAGE_WIDTH = 128
IMAGE_HEIGHT = 120
REDUCE_WIDTH = 4
REDUCE_HEIGHT = 4
INPUT_SIZE = (IMAGE_WIDTH * IMAGE_HEIGHT) / (REDUCE_WIDTH * REDUCE_HEIGHT)

TEST_EXPRESSION = "TEST_EXPRESSION"
TEST_DIRECTION = "TEST_DIRECTION"
TEST_SUNGLASSES = "TEST_SUNGLASSES"
OUTPUT_EXPRESSION = 4
OUTPUT_DIRECTION = 4
OUTPUT_SUNGLASSES = 1

MAX_TARGET = 0.9
MIN_TARGET = 0.1
AVERAGE_TARGET = 0.5
